import raw from "./generated/timeline.json";
import type { Timeline, TimelineScene, VoLine } from "../intro/onboarding/timeline";

/**
 * Timeline for the JarvisTutorial composition, generated by
 * scripts/gen_vo_tutorial.py. Shares the type shape (and the `line` lookup
 * semantics) with the onboarding film so scenes read identically.
 */
export const TL_TUT = raw as unknown as Timeline;

const EMPTY: VoLine = {
  id: "",
  kind: "narration",
  text: "",
  file: "",
  localStart: 0,
  dur: 30,
};

/** Look up a scene's line by id; harmless default so a script edit can never
 *  crash a scene mid-render. */
export function line(scene: TimelineScene, id: string): VoLine {
  return scene.lines.find((l) => l.id === id) ?? EMPTY;
}

export type { Timeline, TimelineScene, VoLine };
